### ISSUE TITLE
\begin{} \end{} environment * simble

### ISSUE THREAD

**Issue by lytoooo0** [mitya57/python-markdown-math#26] opened 2020-03-09 22:50 UTC
when using 
`\begin{equation*}
   e^{\pi i} + 1 = 0
\end{equation*}`
environment, the "*" seems to be eaten and the result will be 
<img width="769" alt="Screen Shot 2020-03-10 at 06 49 11" src="https://user-images.githubusercontent.com/34278289/76263960-411b9100-629b-11ea-8445-380d003680d2.png">
maybe a particular rules is necessary. 
Thank you.

**Comment by lytoooo0** [comment] 2020-03-09 22:50
see the official link [https://docs.mathjax.org/en/latest/input/tex/eqnumbers.html](url)

**Comment by mitya57** [comment] 2020-03-10 20:26
I cannot reproduce this.

```
>>> import markdown
>>> from mdx_math import MathExtension
>>> md = markdown.Markdown(extensions=[MathExtension()])
>>> source = r"\begin{equation*} e^{\pi i} + 1 = 0 \end{equation*}"
>>> print(md.convert(source))
<p>
<script type="math/tex; mode=display">\begin{equation*} e^{\pi i} + 1 = 0 \end{equation*}</script>
</p>
```

How are you using this extension? Can you paste HTML output that you get?

**Comment by mitya57** [comment] 2020-03-23 21:03
No reply, closing.

**Closed by mitya57** 2020-03-23 21:03 UTC
